{% set name = "RUPTURA" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ruptura-{{ version }}.tar.gz
  sha256: 0bee44d066554c9028497f840b81eae94be0eede6cd30062e75d5f8666f59dbc

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - python
    - setuptools >=42
    - pybind11 >=2.10.0
    - pip
  run:
    - python
    - matplotlib-base >=3
    - numpy >=1
    - pybind11 >=2
    - setuptools >=42

test:
  imports:
    - ruptura
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/iRASPA/RUPTURA
  summary: "A simulation package to compute breakthrough curves and IAST mixture predictions."
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - AddYourGitHubIdHere
